import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import LoadingApplicationContextProvider from '@/utils/loadingApplicationContext/context';
import LoadingContextProvider from '@/utils/loadingContext/context';
import ToastContextProvider from '@/utils/toastContext/context';
import ToastSweetalert2ContextProvider from '@/utils/toastSweetalert2Context/context';

const fontAegeaSans = localFont({
  src: [
    {
      path: '../../public/assets/fonts/Aegea-Sans-Light.d3b78a0a4de1a862.otf',
      weight: '300',
    },
    {
      path: '../../public/assets/fonts/Aegea-Sans-Regular.9dac02ec74201e14.otf',
      weight: '400',
    },
    {
      path: '../../public/assets/fonts/Aegea-Sans-Medium.1d201be2063b3dd3.otf',
      weight: '500',
    },
    {
      path: '../../public/assets/fonts/Aegea-Sans-Bold.533e1942d5a10f7a.otf',
      weight: '700',
    },
  ],
  variable: '--font-aegeaSans',
});

export const metadata: Metadata = {
  title: 'Agência virtual - Corsan',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='pt-BR'
      suppressHydrationWarning
      className={fontAegeaSans.variable}
    >
      <head>
        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <link
          rel='shortcut icon'
          href='/assets/favicon-corsan.ico'
          type='image/x-icon'
          sizes='any'
        />
      </head>
      <body className={fontAegeaSans.className}>
        <ToastSweetalert2ContextProvider>
          <ToastContextProvider>
            <LoadingApplicationContextProvider>
              <LoadingContextProvider>{children}</LoadingContextProvider>
            </LoadingApplicationContextProvider>
          </ToastContextProvider>
        </ToastSweetalert2ContextProvider>
      </body>
    </html>
  );
}
